const express = require("express");
const authRoutes = require("./authRoutes");
const moduleRoutes = require("./moduleRoutes.js");
const roleRoutes = require("./roleRoutes.js");
const branchRoutes = require("./branchRoutes");
const prerequisiteRoutes = require("./prerequisiteRoutes.js");
const prerequisiteProgressRoutes = require("./PrerequisiteProgressRoutes.js");
const courseRoutes = require("./courseRouter.js");
const PhaseRouter = require("./phaseRouter.js");
const chapterRouter = require("./chapterRouter.js");
const weekRouter = require("./weekRouter");
const lectureRoutes = require("./lectureRoutes.js");
const assignmentRouter = require("./assignmentRouter.js");
const enrollmentRoutes = require("./enrollmentRoutes");
const adminRoutes = require("./adminRoutes");
const testRoutes = require("./TestRoutes");
const certificateRoutes = require("./certificateRouter.js");
const iqtestRoutes = require("./iqtestRouter.js");
const userRoutes = require("./UserRoutes");
const feedbackRoutes = require("./feedbackRoutes");
const batcheRouter = require("./batchRoutes");
const trainerRouter = require("./trainerRouter");
const studentRouter = require("./studentRouter");
const contactRouter = require("./contactRouter.js");
const sessionCategoryRouter = require("./sessionCategoryRouter.js");
const EventSessionRouter = require("./eventRouter.js");
const webinarRouter = require("./webinarRouter.js");
const workshopRouter = require("./workshopRouter.js");
const OtpRouter = require("./otpRouter.js");
const VideoRouter = require("./videoRouter.js");
const NotesRouter = require("./noteRouter.js");
const internshipSessionsRouter = require("./internshipSessionRouter.js");
const SponsorshipRouter = require("./sponsorshipRouter.js");
const HackathonRouter = require("./hackathonRoutes.js");
const meetingRouter = require("./meetingRoutes.js");
const attendanceRouter = require("./attendanceRoutes.js");
const reportRouter = require("./reportRoutes.js");
const ContactinfoRouter = require("./contactInfoRoutes.js");
const indexRouter = express.Router();

indexRouter.get("/", (req, res) => {
  res.send("LMS API is alive and running...");
});
indexRouter.use("/module", moduleRoutes);
indexRouter.use("/role", roleRoutes);
indexRouter.use("/auth", authRoutes);
indexRouter.use("/branches", branchRoutes);
indexRouter.use("/progress", prerequisiteProgressRoutes);
indexRouter.use("/prerequisite", prerequisiteRoutes);
indexRouter.use("/courses", courseRoutes);
indexRouter.use("/phases", PhaseRouter);
indexRouter.use("/weeks", weekRouter);
indexRouter.use("/chapters", chapterRouter);
indexRouter.use("/lectures", lectureRoutes);
indexRouter.use("/assignments", assignmentRouter);
indexRouter.use("/enrollments", enrollmentRoutes);
indexRouter.use("/admin", adminRoutes);
indexRouter.use("/tests", testRoutes);
indexRouter.use("/certificate", certificateRoutes);
indexRouter.use("/iqtest", iqtestRoutes);
indexRouter.use("/users", userRoutes);
indexRouter.use("/feedback", feedbackRoutes);
indexRouter.use("/batches", batcheRouter);
indexRouter.use("/contact", contactRouter);
indexRouter.use("/meetings", meetingRouter);
indexRouter.use("/attendance", attendanceRouter);
indexRouter.use("/report", reportRouter);
indexRouter.use("/trainer", trainerRouter);
indexRouter.use("/student", studentRouter);
indexRouter.use("/session-category", sessionCategoryRouter);
indexRouter.use("/event", EventSessionRouter);
indexRouter.use("/webinars", webinarRouter);
indexRouter.use("/workshops", workshopRouter);
indexRouter.use("/otp", OtpRouter);
indexRouter.use("/videos", VideoRouter);
indexRouter.use("/notes", NotesRouter);
indexRouter.use("/internship-sessions", internshipSessionsRouter);
indexRouter.use("/sponsorship", SponsorshipRouter);
indexRouter.use("/hackathon", HackathonRouter);
indexRouter.use("/contactinfo", ContactinfoRouter);
module.exports = indexRouter;
